name: Build WinUninstallDoctor MSIX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]  

    runs-on: windows-latest

    env:
      Solution_Name: WinUninstallDoctor.sln
      Wap_Project_Directory: WinUninstallDoctor.Package
      Wap_Project_Path: WinUninstallDoctor.Package\WinUninstallDoctor.Package.wapproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install .NET SDK 
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore $env:Solution_Name

      # Decode the signing certificate from GitHub Secret
      - name: Decode PFX certificate
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.MSIX_CERT_BASE64 }}")
          $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath "GitHubActionsWorkflow.pfx"
          [System.IO.File]::WriteAllBytes($certificatePath, $pfx_cert_byte)

      # Build and generate MSIX package
      - name: Build MSIX Package
        run: |
          msbuild $env:Wap_Project_Path `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=x64 `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:AppxBundle=Never `
            /p:GenerateAppxPackageOnBuild=true `
            /p:AppxPackageSigningEnabled=true `
            /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx `
            /p:PackageCertificatePassword="${{ secrets.MSIX_CERT_PASSWORD }}"

      # Remove the certificate after build
      - name: Remove certificate
        run: Remove-Item -Force "$env:Wap_Project_Directory\GitHubActionsWorkflow.pfx"

      # Upload AppPackages folder
      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinUninstallDoctor-MSIX-${{ matrix.configuration }}
          path: WinUninstallDoctor.Package\AppPackages\
